---

options:

  ###
  ### [DEFAULT]
  ###

  ###
  ### [server]
  ###
  gitea-server-http-port:
    default: 3000
    description: HTTP listen port.
    type: int

  gitea-server-protocol:
    default: 'http'
    description: |
      Gitea web protocol, one of [http, https, http+unix, fcgi, fcgi+unix].
    type: string

  gitea-server-domain:
    default: ''
    description: Config for server.DOMAIN
    type: string

  gitea-server-root-url:
    default: ''
    description: Config for server.ROOT_URL
    type: string

  gitea-server-static-url-prefix:
    default: ''
    description: Config for server.STATIC_URL_PREFIX
    type: string

  gitea-server-ssh-domain:
    default: ''
    description: Config for server.SSH_DOMAIN
    type: string

  ###
  ### [database]
  ###
  gitea-database-type:
    default: 'postgres'
    description: |
      Database to use for Gitea. Currently only postgres is supported.
    type: string

  ###
  ### [security]
  ###

  ###
  ### [oauth2]
  ###

  ###
  ### [log]
  ###
  gitea-log-level:
    default: 'Info'
    description: Log level for Gitea.
    type: string

  ###
  ### [git.timeout]
  ###

  ###
  ### [service]
  ###

  ###
  ### [repository]
  ###
  gitea-repository-max-creation-limit:
    default: 20
    description: >-
      Global maximum creation limit of repositories per user, -1 means no limit.
    type: int

  ###
  ### [repository.upload]
  ###

  ###
  ### [repository.pull-request]
  ###

  ###
  ### [repository.signing]
  ###

  ###
  ### [ui]
  ###

  ###
  ### [admin]
  ###

  ###
  ### [openid]
  ###

  ###
  ### [webhook]
  ###

  ###
  ### [mailer]
  ###
  gitea-mailer-user:
    default: 'kernel-ckctreview'
    description: >-
      Username of mailing user (usually the sender's e-mail address).
    type: string

  gitea-mailer-passwd:
    description: >-
      Password of mailing user. Use `your password` for quoting if you use
      special characters in the password.
    type: string

  ###
  ### [session]
  ###

  ###
  ### [picture]
  ###

  ###
  ### [attachment]
  ###

  ###
  ### [cron.repo_health_check]
  ###

  ###
  ### [cron.update_checker]
  ###

  ###
  ### [metrics]
  ###
  gitea-metrics-token:
    description: >-
      You need to specify the token, if you want to include in the authorization
      the metrics. The same token need to be used in prometheus parameters
      bearer_token or bearer_token_file.
    type: string

  ###
  ### [packages]
  ###

  ###
  ### [storage]
  ###

  ###
  ### [storage.repo-archive]
  ###

  ###
  ### [storage.packages]
  ###

  ###
  ### [proxy]
  ###
  gitea-proxy-proxy-enabled:
    default: 'true'
    description: >-
      Enable the proxy if true, all requests to external via HTTP will be
      affected, if false, no proxy will be used even with environment
      http_proxy/https_proxy
    type: boolean

  gitea-proxy-proxy-url:
    default: 'http://squid.internal:3128/'
    description: >-
      Proxy server URL, support http://, https//, socks://, blank will follow
      environment http_proxy/https_proxy
    type: string

  gitea-proxy-proxy-hosts:
    default: "kernel.org, github.com, *.github.com, launchpad.net, \
      *.launchpad.net, dl.gitea.com"
    description: >-
      Comma separated list of host names requiring proxy. Glob patterns (*) are
      accepted; use ** to match all hosts.
    type: string

  ###
  ### [actions]
  ###

  ###
  ### [storage.actions_log]
  ###

  ###
  ### [storage.actions_artifacts]
  ###

...
