name: Charm

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  handle-charm:
    runs-on:
      - ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Install charmcraft
        run: sudo snap install --classic charmcraft

      - name: Pack charm
        env:
          CHARMCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: "true"
        run: |
          cd charm-source
          charmcraft pack -v

      - name: Upload charm artifact
        uses: actions/upload-artifact@v4
        with:
          name: kteam-gitea
          path: charm-source/*.charm
